<?php

/*
 * This file provides an example about how to start Aplazame checkout
 *
 * NOTE: Contents of this file are displayed on customer browser. USE THE PUBLIC KEY (not the private key)
 */

/*
 * Aplazame's PUBLIC key.
 * You can find your keys on your Aplazame's control panel (https://vendors.aplazame.com/)
 */
$publicKey = '<aplazame PUBLIC API key>';

/*
 * Enable test mode (`Aplazame\Api\Client::ENVIRONMENT_SANDBOX`) or
 *  production mode (`Aplazame\Api\Client::ENVIRONMENT_PRODUCTION`)
 */
$environment = Aplazame\Api\Client::ENVIRONMENT_SANDBOX;

/*
 * Use the ID generated by Aplazame at step2a
 */
$aplazameCheckoutId = '<checkout id from step2a>'
?>

<html>
<head>
    <script
            src="https://aplazame.com/static/aplazame.js"
            data-aplazame="<?php echo $publicKey; ?>"
            data-sandbox="<?php echo ($environment === Aplazame\Api\Client::ENVIRONMENT_SANDBOX) ? 'true' : 'false'; ?>"
    ></script>
</head>
<body>

<h1>
    Aplazame checkout
</h1>

<!-- This fragment is for to assist you about to debug issues. Don't deploy to production! -->
<script>
    var display_error = function (event) {
        var error_container = document.getElementById("error_container");
        console.error(event);
        error_container.innerHTML = event.message
    };

    window.addEventListener('error', display_error);
</script>

<div id="error_container" style="color: red;"></div>
<!-- End fragment -->

<script>
    aplazame.checkout("<?php echo $aplazameCheckoutId; ?>")
</script>
</body>
</html>
